name: CI/CD Pipeline for skewnormlib package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggers

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read       # Required for reading repository content
      id-token: write 

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8  # Specify the Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    # Step 4: Run tests
    - name: Run tests
      run: pytest tests/

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for accessing the repository contents
      id-token: write  # Only deploy from the main branch

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    # Step 3: Install dependencies and build the package
    - name: Build package
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python setup.py sdist bdist_wheel

    # Step 4: Publish to PyPI
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}